### ISSUE TITLE
Commands used to switch the energenie switchs.

### ISSUE THREAD

**Issue by genestealer** [cookejames/sarah-sockets#1]
Great project, I'm doing something very similar using the same libraries and hardware. Would you be happy to share the commands for controlling the switchs. I.E. What are the commands that you are sending via MQTT which are then transmitted over RF?

**Comment by cookejames** [comment]
Its all quite simple really - I'm just sending the correct codes that the rcswitch library provides. Load up https://github.com/sui77/rc-switch/blob/master/examples/ReceiveDemo_Simple/ReceiveDemo_Simple.ino and you can then press remote buttons and capture the codes being sent.

My library simply listens on the MQTT topic 'switch' for codes and republishes them over MQTT.

**Comment by genestealer** [comment]
@cookejames yes I've used the RC switch receives demo before however I do not have access to a remote. Would it perhaps be possible to have a couple of examples out of your database?

**Comment by cookejames** [comment]
Try these. I think you only need to bind with the on command - the switch works out the off command. I've not looked into the scheme used to generate the codes but I imagine someone has reverse engineered it.

The ones starting in 6xx and 7xx are from different remotes.

```
[
  {
    "name": "All",
    "onCommand": 6989581,
    "offCommand": 6989580,
    "id": "566d690af38b565d10591a5e"
  },
  {
    "name": "Livingroom lamp",
    "onCommand": 6989579,
    "offCommand": 6989578,
    "id": "566d6917f38b565d10591a5f"
  },
  {
    "name": "Bedside lamp",
    "onCommand": 6989575,
    "offCommand": 6989574,
    "id": "566d6920f38b565d10591a60"
  },
  {
    "name": "Table lamp",
    "onCommand": 6989583,
    "offCommand": 6989582,
    "id": "566d6924f38b565d10591a61"
  },
  {
    "name": "Conservatory lamp",
    "onCommand": 7592207,
    "offCommand": 7592206,
    "id": "56b5f3a55ef59d285c236ab6"
  },
  {
    "name": "Fairy lights",
    "onCommand": 7592199,
    "offCommand": 7592198,
    "id": "56b5f3c45ef59d285c236ab7"
  }
]
```

**Comment by genestealer** [comment]
Brilliant, many thanks for your help.

In the end I managed to simulate the RF signals using `Eurodomest_0fca6c_00` transmit command to my [RFLink Gateway](https://github.com/Genestealer/Home-Assistant-Configuration/blob/master/includes/lights/rflink_lights.yaml) setup. 

My wiring looks like this: https://github.com/Genestealer/Home-Assistant-RFLink-Gateway-ESP8266

Video of it working: https://goo.gl/photos/SP3hmcF4zNh9t6h86
